### ISSUE TITLE
replace using wildcards not working

### ISSUE THREAD

**Issue by savioret** [cmrcx/phptidy#19]
Hello. Executing this:

`php phptidy.php replace lib/*.php`

Outputs:
Error: File 'lib/*.php' does not exist or is not readable

Just works when I supply a file, without wildcards.
But documentation says I can do it.

**Comment by cmrcx** [comment]
Here the shell wildcard expansion works.

Does the following (in the same shell and directory) find any files?
`ls lib/*.php`

What system do you use?

**Comment by savioret** [comment]
`ls` works but I'm using windows 10 with [msys2](https://www.msys2.org/)
I've tried with the _Windows Subsystem for Linux_ and seems to work, however I cannot make it traverse the whole tree in a recursive way. Is this feature available ?

Thanks.

**Comment by cmrcx** [comment]
How do you try to "traverse the whole tree"?

**Comment by savioret** [comment]
Let's say I have:

```
src/
    |- Models/
    |- Templates/
    |     - Include/
    - lib/
```

I'd like that executing 
`php phptidy.php replace src/*.php`

would execute the tidy on src and all files of all subfolders

**Comment by cmrcx** [comment]
```
cd src
php ../phptidy.php replace
```

**Comment by savioret** [comment]
```
php ../phptidy.php replace
Using configuration file ./.phptidy-config.php
Find functions and includes
Process files
Write cache file ./.phptidy-cache
```
But nothing changed. Seems it not finding any file.

**Comment by cmrcx** [comment]
You have to set the $project_files array in the config file. To make it an almost recursive search you could use multiple stars like this:
`$project_files = array("*.php", "*/*.php", "*/*/*.php", "*/*/*/*.php");`

On the shell you could use the globstar option: https://stackoverflow.com/questions/1690809/what-expands-to-all-files-in-current-directory-recursively
But for a whole project a config file should make more sense.
