### ISSUE TITLE
use break instead of continue in switch

### ISSUE THREAD

**Issue by schmunk42** [cmrcx/phptidy#21]
Getting those with 3.2 and PHP 7.3.11 
```
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /app/vendor/cmrcx/phptidy/phptidy.php on line 960
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /app/vendor/cmrcx/phptidy/phptidy.php on line 1003
```

So, I looks like it should be using `break` or `continue 2`?

**Comment by cmrcx** [comment]
That's indeed a mistake, but it does not have any implication besides the warning. Thanks for reporting!

**Comment by schmunk42** [comment]
Could you also tag a release, please.

**Comment by cmrcx** [comment]
I'm going to test it with PHP 7.4 and then make a release.

**Comment by cmrcx** [comment]
Sorry for the delay, I had to update the system first.
