### ISSUE TITLE
indent_curly_brace_open.php not reformatted

### ISSUE THREAD

**Issue by Clicketyclick** [cmrcx/phptidy#24]
[indent_curly_brace_open.php.expected.phptidy.php](https://github.com/cmrcx/phptidy/blob/master/test/indent_curly_brace_open.php.expected.phptidy.php)
does not look like the result I get using PHP 8.1.2-1ubuntu2.11 (cli)

I set:
```
$diff = "diff -u";
$curly_brace_newline = true;
```
expecting 
```php
<?

if (false)
return;

function x() {

if (true) {
}

function &xxx() {
}

{
exit;
}

{}

}
```
to become
```php
<?

if (false)
	return;

function x() 
{
	if (true) 
	{
	}

	function &xxx() 
	{
	}

	{
		exit;
	}
}
```
But sadly - nothing changed. No indented blocks and no wrapping of curly braces.

**Comment by cmrcx** [comment]
For me it works. Do you maybe have short open tags switched off?

**Comment by Clicketyclick** [comment]
[phptidy.zip](https://github.com/cmrcx/phptidy/files/10926399/phptidy.zip)
Ran: `php phptidy.php suffix indent_curly_brace_open.php`
on 
```
PHP 8.2.3 (cli) (built: Feb 14 2023 09:55:52) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.3, Copyright (c) Zend Technologies
```

**Comment by cmrcx** [comment]
Please try this:
php -r 'phpinfo();' | grep short_open_tag

**Comment by BIT-SDUB** [comment]
Has set `short_open_tag = On` in php.ini and now the script indents.
Can it wrap the curly braces as well?
```
if (true) 
{
}
```

**Comment by Clicketyclick** [comment]
short_open_tag = On in php.ini
