### ISSUE TITLE
2 blank lines are added after functions even if $add_blank_lines is set to false in config

### ISSUE THREAD

**Issue by sudar** [cmrcx/phptidy#5]
Steps to reproduce
- Have a PHP file with functions and classes
- Add the following configuration in the config file.

``` php
$add_blank_lines = false;
$add_file_docblock = true;
$fix_docblock_format = true;
$fix_docblock_space = true;
$add_function_docblocks = true;
```
- Run phptidy on the file
- The formatted file will have 2 blank lines after functions.

**Comment by cmrcx** [comment]
What you get with this configuration is 2 blank lines before every function docblock. If you don't want that, you can switch off $fix_docblock_space.

**Comment by sudar** [comment]
Thanks for the clarification. I thought that `$fix_docblock_space` fixed the formatting inside the docblock. Didn't realize that it was used to add two blank lines.
