### ISSUE TITLE
Feature Request: A new config to control the space around ! operator

### ISSUE THREAD

**Issue by sudar** [cmrcx/phptidy#6]
WordPress coding standard expects a space on both sides of the `!` operator and currently it is not possible to achieve this.

eg: 

``` php
if ( !$some_value ) {
```

should be 

``` php
if ( ! $some_value ) {
```

**Comment by cmrcx** [comment]
Please check if the new function does what you need.

**Comment by sudar** [comment]
@cmrcx The new function does what I need.

Thank you very much.
