### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by cmrcx** [cmrcx/phptidy#8]
phptidy does not work on the current PHP 7 prerelease versions, because the function array_splice() is broken in PHP 7: https://bugs.php.net/bug.php?id=70471

I hope this will be fixed until the final release.

**Comment by schmunk42** [comment]
Any chance to simulate the PHP 5 behavior with a custom function?
I really miss this on PHP 7 :(

**Comment by cmrcx** [comment]
I started writing a replacement for array_splice():

```
/**
 * replacement for broken array_splice() in PHP 7
 * https://bugs.php.net/bug.php?id=70471
 *
 * @param array   $input (reference)
 * @param integer $offset
 * @param integer $length
 * @param array   $replacement ()
 */
function array_splice_fixed(array &$input, $offset, $length=null, array $replacement=array()) {
	if ($offset < 0) {
		$left = array_slice($input, $offset);
	} else {
		$left = array_slice($input, 0, $offset);
	}
	if (is_null($length)) {
		$input = array_merge($left,	$replacement);
	} elseif ($length < 0) {
		$input = array_merge($left,	$replacement, array_slice($input, $length));
	} else {
		$input = array_merge($left, $replacement, array_slice($input, $offset + $length));
	}
	for ( $i = 0; $i <= count($replacement); $i++ ) {
		next($input);
	}
}
```

It works in my test script, but not in phptidy so far.

**Comment by cmrcx** [comment]
Can you please test a little bit, before I make the release?

**Comment by schmunk42** [comment]
No problems so far, I tried it in several different projects.

You may also create a `2.18-beta1` or `2.18-rc1` tag first, this would make it much easier to test the newer version (instead of dev-master)

**Comment by cmrcx** [comment]
Thank you very much for testing!

And yes, next time when I ask for testing, I'll make a tag for it. Thanks for the suggestion.

**Comment by schmunk42** [comment]
Good decision to make a 3.0!
